### ISSUE TITLE
ModuleNotFoundError: No module named 'terminaltables'

### ISSUE THREAD

**Issue by cnmeeia** [n0vad3v/actions-stats#1]
➜  actions-stats-master pip3 install terminaltables
Requirement already satisfied: terminaltables in /usr/local/lib/python3.9/site-packages (3.1.10)
➜  actions-stats-master python3 actions-stats.py
Traceback (most recent call last):
  File "/Users/meeia/Downloads/actions-stats-master/actions-stats.py", line 4, in <module>
    from terminaltables import AsciiTable
ModuleNotFoundError: No module named 'terminaltables'
➜  actions-stats-master

**Comment by n0vad3v** [comment]
From your path `/Users/meeia/` I'm supposing you're using MacOS, since I don't have a working MacOS for testing, I'm not sure about how to deal with this 😂.

Searching on Google I've found a possible solution: https://stackoverflow.com/questions/37341614/modules-are-installed-using-pip-on-osx-but-not-found-when-importing , maybe you can have a try.

Good luck!
